### ISSUE TITLE
Error thrown in Python 3.9 on Raspberry Pi

### ISSUE THREAD

**Issue by ofa1** [highwingers/RaspBerryPiAdhan#3]
I set up the program on a freshly installed Raspbian and get the following error when I try to play the audio on Chromecast. I believe that this is related to the default python being version 3.9 as this error is similar to [this](https://bugs.launchpad.net/hplip/+bug/1889280).

```May 24 11:18:26 raspberrypi python3[715]: 192.168.86.84 - - [24/May/2022 11:18:26] "GET /speaker/api/playMedia?deviceName=Kitchen%20wifi&mediaUrl=%2Fstatic%2Fmedia%2Faz>
May 24 11:18:26 raspberrypi python3[715]: Traceback (most recent call last):
May 24 11:18:26 raspberrypi python3[715]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 2464, in __call__
May 24 11:18:26 raspberrypi python3[715]:     return self.wsgi_app(environ, start_response)
May 24 11:18:26 raspberrypi python3[715]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 2450, in wsgi_app
May 24 11:18:26 raspberrypi python3[715]:     response = self.handle_exception(e)
May 24 11:18:26 raspberrypi python3[715]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1867, in handle_exception
May 24 11:18:26 raspberrypi python3[715]:     reraise(exc_type, exc_value, tb)
May 24 11:18:26 raspberrypi python3[715]:   File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
May 24 11:18:26 raspberrypi python3[715]:     raise value
May 24 11:18:26 raspberrypi python3[715]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
May 24 11:18:26 raspberrypi python3[715]:     response = self.full_dispatch_request()
May 24 11:18:26 raspberrypi python3[715]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
May 24 11:18:26 raspberrypi python3[715]:     rv = self.handle_user_exception(e)
May 24 11:18:26 raspberrypi python3[715]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
May 24 11:18:26 raspberrypi python3[715]:     reraise(exc_type, exc_value, tb)
May 24 11:18:26 raspberrypi python3[715]:   File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
May 24 11:18:26 raspberrypi python3[715]:     raise value
May 24 11:18:26 raspberrypi python3[715]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
May 24 11:18:26 raspberrypi python3[715]:     rv = self.dispatch_request()
May 24 11:18:26 raspberrypi python3[715]:   File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
May 24 11:18:26 raspberrypi python3[715]:     return self.view_functions[rule.endpoint](**req.view_args)
May 24 11:18:26 raspberrypi python3[715]:   File "/home/pio/RaspBerryPiAdhan/www/views/speaker.py", line 28, in playMedia
May 24 11:18:26 raspberrypi python3[715]:     mediaStatus = chromecast().play(device, media)
May 24 11:18:26 raspberrypi python3[715]:   File "/home/pio/RaspBerryPiAdhan/www/lib/chromecast.py", line 40, in play
May 24 11:18:26 raspberrypi python3[715]:     return self.chromecastPlay(deviceName, media)
May 24 11:18:26 raspberrypi python3[715]:   File "/home/pio/RaspBerryPiAdhan/www/lib/chromecast.py", line 49, in chromecastPlay
May 24 11:18:26 raspberrypi python3[715]:     cast.wait()
May 24 11:18:26 raspberrypi python3[715]:   File "/usr/local/lib/python3.9/dist-packages/pychromecast/__init__.py", line 446, in wait
May 24 11:18:26 raspberrypi python3[715]:     if not self.socket_client.isAlive():
May 24 11:18:26 raspberrypi python3[715]: AttributeError: 'SocketClient' object has no attribute 'isAlive'

**Comment by ofa1** [comment]
Digging in further, looks like this issue was fixed in `pychromecast` here: https://github.com/home-assistant-libs/pychromecast/issues/425
